### ISSUE TITLE
SCons Warnings

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#112]
This is a fairly well-known issue, but I don't think an issue has been created to document it. Whenever you initiate a build, we get the following warnings:

```bash

    CELLO_ARCH scons arch= linux_gnu
    CELLO_PREC scons prec= double


scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript '/home/mabruzzo/local/SConscript'
File "/home/mabruzzo/enzo-e/build-main/External/SConscript", line 8, in <module>

scons: warning: Two different environments were specified for target main_enzo.o,
	but they appear to have the same action: $CXX -o $TARGET -c $CXXFLAGS $CCFLAGS $_CCCOMCOM $SOURCES
```

I'm most concerned about the warning that states: `"Two different environments ..."`. This has been around since I was a new user and it definitely tripped me up a bunch when I was getting started. If at all possible, it would be nice to resolve this warning.

The other warning is much newer; I think it only started to appear after PR #46 was merged into master. I'm a little doubtful that anything can be done about this one (or whether anything should be done)

**Comment by pgrete** [comment]
Depending on how far @forrestglines CMake experiments went, it may be worth considering CMake as an alternative to SCons at some point.
One main advantages that I see is that Charm++ could be more easily integrated as a dependency (and potentially build in-line).

**Comment by mabruzzo** [comment]
Yeah, I agree. I generally prefer CMake to SCons. But I guess it all depends on how difficult the transition would be.

CMake would also make integration of Kokkos considerably easier, right? (As I recall, you and Forrest got Kokkos to compile in a hacky way that won't necessarily generalize, to other clusters)

An added bonus of CMake is much better IDE support (I'm not sure how applicable that is for most Enzo-E developers)

**Comment by forrestglines** [comment]
I echo the preference for CMake. My experiment didn't get very far since I couldn't figure out how to get CMake to build the Charm++ interface files in the right order. It was also my first CMake project from scratch, so I didn't really know what I was doing.
