### ISSUE TITLE
Broken Readthedocs Preview

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#129]
The automatic ReadtheDocs preview-builds seem to be broken. This is evident in PR #128 (which only changes 2 lines and doesn't touch any of the documentation).

(I think this is also causing the preview-builds to fail for PR #113.)

Looking at the error-messages I think some python dependency got updated and is now incompatible with the rest of our build environment.

I'm happy to try to resolve this myself. I'm just not sure where these builds are configured (or if I have privileges to access that stuff). Can somebody point me in the right direction? (maybe @brittonsmith)

**Comment by jobordner** [comment]
This issue looks relevant: https://github.com/sphinx-doc/sphinx/issues/9727

**Comment by mabruzzo** [comment]
I think you're absolutely right. The solution seems to be to pin `docutils` to `<0.18` (or to update the version of sphinx that we're using).

I suspect that preview builds were enabled using [these instructions](https://docs.readthedocs.io/en/stable/pull-requests.html). So to fix it, I _think_ that we need to modify the build settings through the enzo-e project page on ReadTheDocs site.

I think that currently, only you and Britton have admin access to that site (so one of you needs to fix it). Alternatively, I could take a shot at fixing this, but I would need to be linked to the project.

**Comment by mabruzzo** [comment]
This seems to have been resolved. I'm not sure whether

- James or Britton fixed this issue, or 
- if the issue resolved itself (e.g. maybe sphinx updated its dependencies).

**Comment by brittonsmith** [comment]
I encountered this recently somewhere else and banged against it for a while, to no avail. Then it just went away. It seems to be something that RTD corrected themselves.
