### ISSUE TITLE
Passing particles from parent to child during ICs

### ISSUE THREAD

**Issue by aemerick** [enzo-project/enzo-e#15]
Currently, there is a bug that prevents passing particles from a parent blocks (i.e. the root grid) to child blocks during initialization. This is preventing ICs with both a large number of particles and a large number of highly refined blocks, but a reasonable number of root-grid blocks. Although reading these particles into each child block works, this can take an incredibly long time for large particle lists / block counts. 

More generally there may be a need to do something creative to read in VERY large particle ICs for VERY large root-grids, but that is longer term and solutions may be problem-type specific.

**Comment by jwise77** [comment]
I _think_ this was fixed in #49. Tentatively closing.
