### ISSUE TITLE
`input/Cosmology/method_cosmology` single-precision bugs

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#154]
While working on PR #125, I stumbled onto an error with running:
- `input/Cosmology/method_cosmology-1.in`
- `input/Cosmology/method_cosmology-8.in`

when using an executable that is compiled for single-precision without the `-ffast-math` flag (which is currently the default compilation option).

The problem seems to be related to particles and gravity. Since I'm not super familiar with these components of the codebase, I haven't really dug into the problem. To make things easier for someone else (with more expertise) to dig into this, I have attached outputs from 3 different runs with `input/Cosmology/method_cosmology-1.in`: 

1. single-precision, without the `-ffast-math` flag: [log-file](https://pastebin.com/GRFP58LC) & [single.tar.gz](https://github.com/enzo-project/enzo-e/files/8240004/single.tar.gz). **(this is the run that fails with an error)**
2. single-precision, with the `-ffast-math` flag:  [log-file](https://pastebin.com/adNESExa) & [single-ffast-math.tar.gz](https://github.com/enzo-project/enzo-e/files/8240005/single-ffast-math.tar.gz)
3. double-precision, without the `-ffast-math` flag: [log-file](https://pastebin.com/dD6DEDic) & [double-snapshots.tar.gz](https://github.com/enzo-project/enzo-e/files/8240013/double-snapshots.tar.gz) (because of the increased size of these snapshots, this tar file just includes snapshots for cycles 0-2 and the last cycle)

As you can see from the single-precision log-file, there are all sorts of errors related to `nan`s, and then the code ultimately crashes while complaining about invalid particle positions. I took a quick peak at particle positions after the first cycle (using `yt`) and they seem to also be `nan`s.

If you look at the log file for the single-precision, `-ffast-math` run, there are some hints that the gravity solver also encounters some issues with `nan`s. However, these problems are somewhat suppressed because of floating-point optimizations that `-ffast-math` enables that are related to `nan`s (e.g. like the `-ffinite-math` optimizations). I the suspect this run only reaches the expected final timestep because the timesteps are primarily getting set by the fluid solver/cosmology method. In any case, I suspect that the issues are still present for this solver to some degree... (and would recommend that people avoid using Cosmology in single precision mode)

**Comment by jobordner** [comment]
Try changing `"double"` in the `Particle : dark : constants` parameter to `"default"`.  FWI, the `method_cosmology` tests are old and should be retired; the test_cosmo-_solver_.in parameter files are preferred.
