### ISSUE TITLE
Remove SCons wording from docs

### ISSUE THREAD

**Issue by fearmayo** [enzo-project/enzo-e#195]
SCons is still mentioned in the docs in places (e.g. in the Testing Infrastructure part) and could be removed.

**Comment by mabruzzo** [comment]
I just performed `grep -rI "scons" .` from the root of the `doc` subdirectory and I only found 1 mention of Scons. Specifically the CMake Primer mentions that Enzo-E historically used Scons before migrating to CMake.

Consequently, I think this issue is resolved and I'm closing it.
