### ISSUE TITLE
`Adapt:density` Problem with coarsening

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#286]
I've been working on setting up some AMR regression tests and I've stumbled onto a puzzling bug with coarsening while using `Adapt:density`.

[Here](https://pastebin.com/TsTmGcvE) is a link to a sample configuration file. It sets up multiple axis-aligned sound waves to be run by the PPM solver. As you probably know, sound waves are initialized by introducing perturbations relative to multiple quantities (including density).

This problem is set up with a density refinement threshold that should trigger refinement when: $\rho - \rho_{\rm bkg} > 0.9 * \delta_{\rm max}$, where $\delta_{\rm max}$ denotes the maximum initial density perturbation. The problem blocks **should** be configured to coarsen when no cells have density in excess of this threshold.

While the simulation definitely performs refinement correctly, it doesn't appear to coarsen. This is illustrated in the following plot, which shows a single sound wave (all the points have a fixed y,z position) at various snapshots in times. There are a few things to note:
- the plot shows the perturbations in the quantities measured with respect to the background values
- the vertical gray dotted lines show block boundaries
- the horizontal black dashed line shows the density threshold for refinement
- the points for density are directly underneath the points for x-momentum

![example-output](https://user-images.githubusercontent.com/28722054/222501305-dc57107f-fb17-4056-b83d-9fbacfe2aca4.png)

For reference, I generated this plot with [this script](https://pastebin.com/79jMLgzd). I also made another version of this same plot where I have included data from all of the parallel sound waves - as expected density doesn't show any variation with (y,z) position (I only looked by eye - but it definitely shouldn't prevent coarsening).

There's a reasonable chance that I've messed something up in my parameter file. @jobordner do you see anything obvious?

**Comment by jobordner** [comment]
@mabruzzo Try the following fix:

```
diff --git a/src/Cello/mesh_RefineDensity.cpp b/src/Cello/mesh_RefineDensity.cppindex bf772f493..5d3ff7452 100644
--- a/src/Cello/mesh_RefineDensity.cpp
+++ b/src/Cello/mesh_RefineDensity.cpp
@@ -86,7 +86,7 @@ int RefineDensity::apply_
       for (int ix=gx; ix<mx-gx; ix++) {
        int i = ix + mx*(iy + my*iz);
        if (array[i] > min_refine_)  any_refine  = true;
-       if (array[i] < max_coarsen_) all_coarsen = false;
+       if (array[i] > max_coarsen_) all_coarsen = false;
       }
     }
   }
```
