### ISSUE TITLE
Metal density field errors

### ISSUE THREAD

**Issue by aemerick** [enzo-project/enzo-e#40]
As I found about a month ago in my version of Enzo-E (https://github.com/aemerick/enzo-e/tree/isolated-galaxy), the metal density field kept showing errors that grew with the number of cycles and appeared in grid-like patterns. But this only occurred when running in parallel, and showed no issues on a single core. I also tried this on the solver-dd branch (since mine has quite a few changes), and this still occured.

I came up with a minimal example that shows this problem in my branch and the master branch. In my prior tests of this the issue only arose in the metal density field (and really any colour field I had) but not elsewhere. The attached test seems to show issues in other fields as well.

Interestingly, the behavior changes each time this is run (at least when using the master branch..... this is not something I found originally). Sometimes running in parallel works OK, sometimes it doesn't. I was testing with 2 and 4 cores.

You do have to add metal_density as a field to be refreshed in the PPM method (``enzo_EnzoMethodPpm.cpp``) to run this.

[ppm_metal.txt](https://github.com/enzo-project/enzo-e/files/4624297/ppm_metal.txt)

**Comment by mabruzzo** [comment]
I am having some difficulty reproducing the error and I want be sure that I am not doing something incorrect. 

1. I inserted ``refresh(ir)->add_field(field_descr->field_id("metal_density")); `` at line 44 of ``enzo_EnzoMethodPpm.cpp`` (in the constructor of ``EnzoMethodPpm``).  I was using the master branch.
2. I tried to use this script, [reproduce.py](https://pastebin.com/raw/DvNY3rFW) to reproduce the error (I executed ``python reproduce.py ppm 10`` - meaning I ran the parallel simulation 10 times).

I was running this on my local laptop which was using the ``netlrts-linux-x86_64`` build of charm++.

If this all seems right to you would you mind confirming that the python script reproduces the error for you on your machine. All you need to do is modify the paths at the top of the script and execute the above command (you can ignore the vlct related paths)

**Comment by aemerick** [comment]
Hey @mabruzzo thanks for this. It looks like I had been running with the `multicore-linux-x86_64   --with-production` build options for charm++... I'll try `netlrts-linux-x86_64` and see if I notice any differences. 

Side note, why does your script have `++p` instead of just `+p` for the charm run command? Using `++` does not work for me.

**Comment by aemerick** [comment]
Actually. Now I know why I compiled with `multicore-linux-x86_64` before. For some reason `netlrts-linux-x86_64` does not work for me. It just hangs when running with `+p` > 1 (and I do have to specify either `++local` or `++mpiexec` when in this mode).... Is this expected? or am I screwing something else up here?

**Comment by mabruzzo** [comment]
For the ``netlrts-linux-x86_64`` version I think that ``++p N`` and ``+pN`` are equivalent. According to the [documentation](https://charm.readthedocs.io/en/latest/charm++/manual.html#command-line-options), the former can be used for a program executed over a network while the latter specifies the number of worker nodes.

The need to use ``++mpiexec`` is odd. I've never had to do that. It always seemed to connect for me via ssh. From what I can tell, executing ``charmrun`` under ``netlrts-linux-x86_64`` tries to ssh back into your own machine (It demands a your password every time unless you set up an ssh key-pair on your local machine from your local machine). 

If you don't have an ssh server installed running on your laptop to host connections, it might not work.

I'll try compiling charm with ``multicore-linux-x86_64 --with-production`` and see if I can reproduce your error then.

**Comment by aemerick** [comment]
Thanks. I think running in `++local` avoids ssh-ing back into the machine, but this is what is failing when running without this. I don't have an ssh server installed, so that is definitely the issue. 

But with `++local` it works fine with `+p1`, but charm hangs at initialization with anything more than that. Thanks for trying with multicore

**Comment by mabruzzo** [comment]
I just tried out ``multicore-linux-x86_64`` and was able to reproduce the issue after 3 attempts.

I think this means that either:
1. This is a problem with ``multicore-linux-x86_64``.
2. Maybe this is a general problem that is only manifesting right now using ``multicore-linux-x86_64`` because the timings of the IPC are different (presumably faster) than ``netlrts-linux-x86_64``.

**Comment by aemerick** [comment]
Well, glad to see I'm not crazy. Thanks for reproducing this. I just tried compiling `multicore-linux-x86_64` in debug mode and still had the same issues (sometimes working, sometimes crashing, sometimes not crashing but with errors).

**Comment by jobordner** [comment]
@aemerick Yes, multicore can be problematic (it's similar to SMP mode I think).  I've never seen this problem with netlrts, and couldn't reproduce the problem with netlrts.

**Comment by aemerick** [comment]
@jobordner Ah Ok. Thanks for the clarification. So then this issue is likely a non-issue if @mabruzzo did not reproduce it on the netrtls build.... I'll try and figure out whats going on on my end with the netlrts build.

**Comment by aemerick** [comment]
I ended up updating and re-installing charm, as well as ensuring my ssh client and server were set up correctly and this fixed my issues with netlrts. However, I still have to run with `++local`, but otherwise seems to be behaving OK. 

I'm going to close this issue.
