### ISSUE TITLE
HDF5 Error

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#52]
I was running a large simulation on Frontera (4096 PEs) and the program weirdly crashed while writing an HDF5 file. This error seems to be non-deterministic and rare: 

- I had already run 2 simulations of the same size which each wrote about 300 hdf5 files to disk
- The simulation in which the error arose had already written 130 outputs. Plus after restart the same did not happen again.

I'm not sure how much can be done about this but wanted to report it

**Here is the traceback written to stdout:**

> [1963] Stack Traceback:
>   [1963:0] enzo-p 0xb679a5 t_()
>   [1963:1] enzo-p 0xb24594 FileHdf5::file_close()
>   [1963:2] enzo-p 0xb16bb8 OutputData::close()
>   [1963:3] enzo-p 0xae73f1 Problem::output_write(Simulation*, int, char*)
>   [1963:4] enzo-p 0xae727d Problem::output_wait(Simulation*)
>   [1963:5] enzo-p 0xae7014 Simulation::r_write(CkReductionMsg*)
>   [1963:6] enzo-p 0xae6ef8 Block::p_output_write(int, int)
>   [1963:7] enzo-p 0xa42252 CkIndex_Block::_call_p_output_write_marshall13(void*, void*)
>   [1963:8] enzo-p 0x61b30f CkDeliverMessageReadonly
>   [1963:9] enzo-p 0x64c844 CkLocRec::invokeEntry(CkMigratable*, void*, int, bool)
>   [1963:10] enzo-p 0x6b4ed4 CkIndex_CkArray::_call_recvBroadcast_CkMessage(void*, void*)
>   [1963:11] enzo-p 0x620a1b
>   [1963:12] enzo-p 0x61f7ec _processHandler(void*, CkCoreState*)
>   [1963:13] enzo-p 0x7ec0e4 CsdScheduler
>   [1963:14] enzo-p 0x7e9265 ConverseInit
>   [1963:15] enzo-p 0x6111e2 charm_main
>   [1963:16] libc.so.6 0x2ad9b62de555 __libc_start_main
>   [1963:17] enzo-p 0x56c7f9
> [1963] Stack Traceback:
>   [1963:0] libhdf5.so.103 0x2ad9b14bdc8b H5F__close_cb
>   [1963:1] libhdf5.so.103 0x2ad9b1545a9e
>   [1963:2] libhdf5.so.103 0x2ad9b16241d0 H5SL_try_free_safe
>   [1963:3] libhdf5.so.103 0x2ad9b1545999 H5I_clear_type
>   [1963:4] libhdf5.so.103 0x2ad9b14acd9e H5F_term_package
>   [1963:5] libhdf5.so.103 0x2ad9b13f499a H5_term_library
>   [1963:6] libc.so.6 0x2ad9b62f5ce9
>   [1963:7] libc.so.6 0x2ad9b62f5d37
>   [1963:8] libmpi.so.12 0x2ad9b599a406 MPL_exit
>   [1963:9] libmpi.so.12 0x2ad9b5518229
>   [1963:10] libmpi.so.12 0x2ad9b504d153
>   [1963:11] libmpi.so.12 0x2ad9b4f582fd MPI_Abort
>   [1963:12] enzo-p 0x7e8457 CmiAbort
>   [1963:13] enzo-p 0xb679a5 t_()
>   [1963:14] enzo-p 0xb24594 FileHdf5::file_close()
>   [1963:15] enzo-p 0xb16bb8 OutputData::close()
>   [1963:16] enzo-p 0xae73f1 Problem::output_write(Simulation*, int, char*)
>   [1963:17] enzo-p 0xae727d Problem::output_wait(Simulation*)
>   [1963:18] enzo-p 0xae7014 Simulation::r_write(CkReductionMsg*)
>   [1963:19] enzo-p 0xae6ef8 Block::p_output_write(int, int)
>   [1963:20] enzo-p 0xa42252 CkIndex_Block::_call_p_output_write_marshall13(void*, void*)
>   [1963:21] enzo-p 0x61b30f CkDeliverMessageReadonly
>   [1963:22] enzo-p 0x64c844 CkLocRec::invokeEntry(CkMigratable*, void*, int, bool)
>   [1963:23] enzo-p 0x6b4ed4 CkIndex_CkArray::_call_recvBroadcast_CkMessage(void*, void*)
>   [1963:24] enzo-p 0x620a1b
>   [1963:25] enzo-p 0x61f7ec _processHandler(void*, CkCoreState*)
>   [1963:26] enzo-p 0x7ec0e4 CsdScheduler
>   [1963:27] enzo-p 0x7e9265 ConverseInit
>   [1963:28] enzo-p 0x6111e2 charm_main
>   [1963:29] libc.so.6 0x2ad9b62de555 __libc_start_main
>   [1963:30] enzo-p 0x56c7f9
> [1595807695.210587] [c111-094:179807:0]          ib_md.c:1063 UCX  WARN  IB: ibv_fork_init() was disable\
> d or failed, yet a fork() has been issued.
> [1595807695.210601] [c111-094:179807:0]          ib_md.c:1064 UCX  WARN  IB: data corruption might occur\
>  when using registered memory.

**Here is the error message written to stderr:**

> HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 0:
>   #000: H5C.c line 5457 in H5C_flush_invalidate_ring(): dirty entry flush destroy failed
>     major: Object cache
>     minor: Unable to flush data from cache
>   #001: H5C.c line 6133 in H5C__flush_single_entry(): Can't write image to file
>     major: Object cache
>     minor: Unable to flush data from cache
>   #002: H5Fio.c line 165 in H5F_block_write(): write through page buffer failed
>     major: Low-level I/O
>     minor: Write failed
>   #003: H5PB.c line 1028 in H5PB_write(): write through metadata accumulator failed
>     major: Page Buffering
>     minor: Write failed
>   #004: H5Faccum.c line 645 in H5F__accum_write(): file write failed
>     major: Low-level I/O
>     minor: Write failed
>   #005: H5FDint.c line 258 in H5FD_write(): driver write request failed
>     major: Virtual File Layer
>     minor: Write failed
>   #006: H5FDsec2.c line 811 in H5FD_sec2_write(): file write failed: time = Sun Jul 26 18:54:00 2020
> , filename = './cloud_08.2500/cloud-data-1963.h5', file descriptor = 49, errno = 5, error message = 'Inp\
> ut/output error', buf = 0x1ac7ab8, total write size = 1224, bytes this sub-write = 1224, bytes actually \
> written = 18446744073709551615, offset = 73417080
>     major: Low-level I/O
>     minor: Write failed
>   #007: H5Fint.c line 1130 in H5F__dest(): unable to flush cached data (phase 2)
>     major: File accessibilty
>     minor: Unable to flush data from cache
>   #008: H5Fint.c line 1912 in H5F__flush_phase2(): unable to flush metadata accumulator
>     major: Low-level I/O
>     minor: Unable to flush data from cache
>   #009: H5Faccum.c line 1033 in H5F__accum_flush(): file write failed
>     major: Low-level I/O
>     minor: Write failed
>   #010: H5FDint.c line 258 in H5FD_write(): driver write request failed
>     major: Virtual File Layer
>     minor: Write failed
>   #011: H5FDsec2.c line 811 in H5FD_sec2_write(): file write failed: time = Sun Jul 26 18:53:04 2020
> , filename = './cloud_08.2500/cloud-data-1963.h5', file descriptor = 49, errno = 5, error message = 'Inp\
> ut/output error', buf = 0x1ac7ab8, total write size = 1224, bytes this sub-write = 1224, bytes actually \
> written = 18446744073709551615, offset = 73417080
>     major: Low-level I/O
>     minor: Write failed
>   #012: H5Fint.c line 1901 in H5F__flush_phase2(): unable to flush metadata cache
>     major: Object cache
>     minor: Unable to flush data from cache
>   #013: H5AC.c line 732 in H5AC_flush(): Can't flush cache
>     major: Object cache
>     minor: Unable to flush data from cache
>   #014: H5C.c line 1150 in H5C_flush_cache(): flush ring failed
>     major: Object cache
>     minor: Unable to flush data from cache
>   #015: H5C.c line 5872 in H5C__flush_ring(): Can't flush entry
>     major: Object cache
>     minor: Unable to flush data from cache
>   #016: H5C.c line 6133 in H5C__flush_single_entry(): Can't write image to file
>     major: Object cache
>     minor: Unable to flush data from cache
>   #017: H5Fio.c line 165 in H5F_block_write(): write through page buffer failed
>     major: Low-level I/O
>     minor: Write failed
>   #018: H5PB.c line 1028 in H5PB_write(): write through metadata accumulator failed
>     major: Page Buffering
>     minor: Write failed
>   #019: H5Faccum.c line 645 in H5F__accum_write(): file write failed
>     major: Low-level I/O
>     minor: Write failed
>   #020: H5FDint.c line 258 in H5FD_write(): driver write request failed
>     major: Virtual File Layer
>     minor: Write failed
>   #021: H5FDsec2.c line 811 in H5FD_sec2_write(): file write failed: time = Sun Jul 26 18:52:09 2020
> , filename = './cloud_08.2500/cloud-data-1963.h5', file descriptor = 49, errno = 5, error message = 'Inp\
> ut/output error', buf = 0x1ac7ab8, total write size = 1224, bytes this sub-write = 1224, bytes actually \
> written = 18446744073709551615, offset = 73417080
>     major: Low-level I/O
>     minor: Write failed
>   #022: H5Fint.c line 1881 in H5F__flush_phase2(): unable to flush metadata cache
>     major: Object cache
>     minor: Unable to flush data from cache
>   #023: H5AC.c line 732 in H5AC_flush(): Can't flush cache
>     major: Object cache
>     minor: Unable to flush data from cache
>   #024: H5C.c line 1150 in H5C_flush_cache(): flush ring failed
>     major: Object cache
>     minor: Unable to flush data from cache
>   #025: H5C.c line 5872 in H5C__flush_ring(): Can't flush entry
>     major: Object cache
>     minor: Unable to flush data from cache
>   #026: H5C.c line 6133 in H5C__flush_single_entry(): Can't write image to file
>     major: Object cache
>     minor: Unable to flush data from cache
>   #027: H5Fio.c line 165 in H5F_block_write(): write through page buffer failed
>     major: Low-level I/O
>     minor: Write failed
>   #028: H5PB.c line 1028 in H5PB_write(): write through metadata accumulator failed
>     major: Page Buffering
>     minor: Write failed
>   #029: H5Faccum.c line 645 in H5F__accum_write(): file write failed
>     major: Low-level I/O
>     minor: Write failed
>   #030: H5FDint.c line 258 in H5FD_write(): driver write request failed
>     major: Virtual File Layer
>     minor: Write failed
>   #031: H5FDsec2.c line 811 in H5FD_sec2_write(): file write failed: time = Sun Jul 26 18:51:14 2020
> , filename = './cloud_08.2500/cloud-data-1963.h5', file descriptor = 49, errno = 5, error message = 'Inp\
> ut/output error', buf = 0x1ac7ab8, total write size = 1224, bytes this sub-write = 1224, bytes actually \
> written = 18446744073709551615, offset = 73417080
>     major: Low-level I/O
>     minor: Write failed
> 1963 119516.09  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> 1963 119516.09 ERROR disk_FileHdf5.cpp:143
> 1963 119516.09 ERROR FileHdf5::file_close
> 1963 119516.09 ERROR Return value -1 closing file ./cloud_08.2500/cloud-data-1963.h5
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_Z2t_v+0x1b) [0xb6794b]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN8FileHdf510file_closeEv+0x1c4) [0xb24594]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN10OutputData5closeEv+0x18) [0xb16bb8]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN7Problem12output_writeEP10SimulationiPc+0\
> x81) [0xae73f1]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN7Problem11output_waitEP10Simulation+0x20d\
> ) [0xae727d]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN10Simulation7r_writeEP14CkReductionMsg+0x\
> 74) [0xae7014]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN5Block14p_output_writeEii+0xc8) [0xae6ef8\
> ]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN13CkIndex_Block31_call_p_output_write_mar\
> shall13EPvS0_+0x92) [0xa42252]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(CkDeliverMessageReadonly+0x3f) [0x61b30f]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN8CkLocRec11invokeEntryEP12CkMigratablePvi\
> b+0xb4) [0x64c844]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_ZN15CkIndex_CkArray29_call_recvBroadcast_Ck\
> MessageEPvS0_+0x374) [0x6b4ed4]
> 1963 119516.12 EXIT :0 
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p() [0x620a1b]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(_Z15_processHandlerPvP11CkCoreState+0x112c) \
> [0x61f7ec]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(CsdScheduler+0x444) [0x7ec0e4]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(ConverseInit+0xaf5) [0x7e9265]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p(charm_main+0x22) [0x6111e2]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /lib64/libc.so.6(__libc_start_main+0xf5) [0x2ad9b62de555]
> 1963 119516.12 EXIT :0
> 1963 119516.12 EXIT /home1/05274/tg845732/enzo-e/bin/enzo-p() [0x56c7f9]

**Comment by pgrete** [comment]
Which environment are you using?
I had a similar problem writing data to disk last week for which it was suggested using impi 19.0.7 instead of the default 19.0.5 (and changing the MPI version fixed it in my case).

**Comment by mabruzzo** [comment]
Ah, that's probably the issue. I have been using 19.0.5. Thanks for the help.

I'm going to close this since it's probably not an issue with the code (I wasn't originally sure).
