### ISSUE TITLE
Circleci cosmo-bcg Timeout Issue in VLCT PR

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#61]
This documents a Circleci problem that initially manifested for PR #9, after merging in changes from PR #12 in commit. The issue first appeared in https://github.com/enzo-project/enzo-e/pull/9/commits/43341c9a140446cac153039b73f98a1ffe7e41f8, which was the first commit pushed to GitHub following the merge.

To briefly summarize the problem, the cosmo-bcg test, added by PR #12, failed when it was run on Circleci due to a timeout. However, neither @jobordner nor myself were able to replicate the issue on our local machines; when running it locally, we each found that the test passed when run locally. @jobordner recently found a work-around for this issue with commit 86b76931f33a52e61718982e2ac52811931752d8.

This is largely being made to archive the discussion that @jobordner and I had about this issue over Slack

**Comment by mabruzzo** [comment]
On October 26th, @jobordner  wrote:

> @mabruzzo It seems to be related to refinement, and I've only been able to verify it on circleci.  Attached are times for the cosmo-bcg test on circleci for the current master and the vlct branch; refinement starts at around cycle 120.
![vlct-cosmo-bcg](https://user-images.githubusercontent.com/28722054/98445763-7a84f480-20e7-11eb-9e1a-3a9566f9e88f.png)

**Comment by mabruzzo** [comment]
@jobordner, I guess the fact that you bypassed this issue with https://github.com/enzo-project/enzo-e/pull/9/commits/86b76931f33a52e61718982e2ac52811931752d8 , by changing the default optimization from O3 to O1, means that this was a compiler bug.

I think this probably resolves the issue, but I'll let you have the last word on whether we should close the issue.

PS: Appologies for mentioning you so many times while moving the discussion thread to GitHub. In hindsight, I probably should probably should have recorded things slightly differently.

**Comment by jobordner** [comment]
@mabruzzo Although I still don't know what specific code is triggering the compiler optimization error, I agree that this issue can be closed.  I don't think we should change O3 to O1 to fix it, however; I did that mainly to test a hypothesis.  I think a better approach would be to configure circleci to use a newer environment than it is currently using. I think that just involves replacing the `image: circleci/python:3.7.2` lines in `.circleci/config.yml` with something else.  I can continue to root out the source of the problem when I can free up some time.

For the sake of further documenting the issue, I've found it's reproducible in Ubuntu 16.04, and the problem is the introduction of gross errors in accelerations along block boundaries starting as soon as cycle 1.  The increase in memory use does not appear to be due to a memory leak, but because the errors are triggering adapt to create more refined grids sooner.

**Comment by mabruzzo** [comment]
Ok, sounds good. I'm going to hold off momentarily on closing it until we agree on how best to fix it.

Looking at [this](https://r4ds.had.co.nz/factors.html?q=catego#modifying-factor-levels), it seems like the circleci has started to create newer images based on the most recent LTS release of Ubuntu (although it's somewhat unclear whether they are describing Ubuntu 18.04 or 20.04).

If I understand everything correctly, I think replacing `image: circleci/python:3.7.2` with `image:cimg/python:3.7.2` will use either Ubuntu 18.04 or 20.04. When I have a chance in the next few days, I'll try this out.

Since this is Circleci related, I'm tagging @brittonsmith, just in case he has anything to add.

**Comment by jobordner** [comment]
Additionally, 3D flux correction tests crash in double precision in the main `enzo-project/enzo-e` master branch, but they don't get flagged as errors.  This is also repeatable in Ubuntu 16.04, and they also run correctly when O3 optimization is lowered to O1.  Single precision works ok (as does cosmo-bcg incidentally).  I suspect addressing this cosmo-bcg issue will address the 3D flux tests failing as well.  (That this doesn't cause the regression tests to fail is a separate issue that needs to be addressed.)

Tail of current enzo-project/enzo-e double-precision test results:

> ```
> 17:58:57 linux_gnu double       FAIL:  0      Incomplete: 15 Pass: 8817          
>    CRASH: test/test_method_flux3-xm.unit
>    CRASH: test/test_method_flux3-xp.unit
>    CRASH: test/test_method_flux3-ym.unit
>    CRASH: test/test_method_flux3-yp.unit
>    CRASH: test/test_method_flux3-zm.unit
>    CRASH: test/test_method_flux3-zp.unit
> END   Enzo-P/Cello ./build.sh: arch = linux_gnu  prec = double  target = test time = 37.36 min
> Test run summary
> 
>    Test runs attempted: 109
>    Test runs started:   109
>    Test runs completed: 103
>    --------------------
>    *** incomplete output: test/test_method_flux3-xm.unit
>    *** incomplete output: test/test_method_flux3-xp.unit
>    *** incomplete output: test/test_method_flux3-ym.unit
>    *** incomplete output: test/test_method_flux3-yp.unit
>    *** incomplete output: test/test_method_flux3-zm.unit
>    *** incomplete output: test/test_method_flux3-zp.unit
>    --------------------
> 
> Exiting testing with success
> Done.
> ```

**Comment by mabruzzo** [comment]
I have now adopted our discussed workaround in PR #62
