### ISSUE TITLE
The load balance tests may need to be skipped on circle-ci since they don't do what's intended

### ISSUE THREAD

**Issue by fearmayo** [enzo-project/enzo-e#75]
We may need to skip the load balancing tests on circle-ci since ssh is not available. At the moment ++local is used in the run argument which defeats the purpose of the tests on circle-ci. Tests are currently located in `test/Balance`

**Comment by jobordner** [comment]
They still run using multiple processes, only the mechanism for communication between the processes changes.  There is no difference in the efficacy of running the load balancing tests using ++local or not when running on a single node.

**Comment by fearmayo** [comment]
Thanks for clarification @jobordner . It came up in PR #73.

**Comment by mabruzzo** [comment]
@fearmayo Sorry for steering you wrong on this.
