### ISSUE TITLE
Hanging adapt-L5-P1 test on Circleci

### ISSUE THREAD

**Issue by mabruzzo** [enzo-project/enzo-e#81]
After the final time that @jobordner merged the master branch into PR #45, the `adapt-L5-P1` test hung when CircleCi compiled the code both in single and double precision mode. He noted that
- this was weird since none of the changes introduced in the PR should have affected that test
- when he sshed into the CircleCi server, the test did seem to run a little slowly
- CircleCi had some warning about exceeding violating concurrency limits. Maybe it was somehow using more cores than requested at some point during the testing

**Comment by jwise77** [comment]
Fixed in #102
