### ISSUE TITLE
Gravity time step.

### ISSUE THREAD

**Issue by stefanarridge** [enzo-project/enzo-e#85]
The gravity time step condition is calculated in Lines 244-287 of [src/Enzo/enzo_EnzoMethodGravity.cpp](https://github.com/enzo-project/enzo-e/blob/master/src/Enzo/enzo_EnzoMethodGravity.cpp):
```
if (cosmology) {
    const int rank = cello::rank();
    enzo_float cosmo_a = 1.0;
    enzo_float cosmo_dadt = 0.0;
    double dt   = block->dt();
    double time = block->time();
    cosmology-> compute_expansion_factor (&cosmo_a,&cosmo_dadt,time+0.5*dt);
    if (rank >= 1) hx*=cosmo_a;
    if (rank >= 2) hy*=cosmo_a;
    if (rank >= 3) hz*=cosmo_a;
  }

  if (ax) {
    for (int iz=gz; iz<mz-gz; iz++) {
      for (int iy=gy; iy<my-gy; iy++) {
	for (int ix=gx; ix<mx-gx; ix++) {
	  int i=ix + mx*(iy + iz*my);
	  dt = std::min(enzo_float(dt),enzo_float(sqrt(hx/(fabs(ax[i]+1e-20)))));
	}
      }
    }
  }
  if (ay) {
    for (int iz=gz; iz<mz-gz; iz++) {
      for (int iy=gy; iy<my-gy; iy++) {
	for (int ix=gx; ix<mx-gx; ix++) {
	  int i=ix + mx*(iy + iz*my);
	  dt = std::min(enzo_float(dt),enzo_float(sqrt(hy/(fabs(ay[i]+1e-20)))));
	}
      }
    }
  }
  if (az) {
    for (int iz=gz; iz<mz-gz; iz++) {
      for (int iy=gy; iy<my-gy; iy++) {
	for (int ix=gx; ix<mx-gx; ix++) {
	  int i=ix + mx*(iy + iz*my);
	  dt = std::min(enzo_float(dt),enzo_float(sqrt(hz/(fabs(az[i]+1e-20)))));
	}
      }
    }
  }

  return 0.5*dt;
}
```
There are a few issues with this:

- The cell widths are multiplied by 'cosmo_a' to convert from comoving to proper coordinates. But there is no equivalent done for the accelerations. It is my understanding that when cosmology is turned on, all field values are all comoving quantities, but I may be wrong about this. In general I think the treatment of units and comoving vs physical quantities needs to be clarified and perhaps needs a separate github issue.
- On the first cycle, the acceleration field is zero everywhere, which means that dt will be sqrt(hx)*1e10, independent of the units used. This means that the gravity time step on the first cycle will be very large, and not physically motivated. In a dark matter only simulation, this will be the time step used, unless the maximum time step is set to be something smaller. At the very least, the '1e-20' should be replaced by an input parameter which can be less arbitrary.
- In general, the timestep depends on the acceleration field from the previous cycle, which is likely not what we want.

**Comment by mabruzzo** [comment]
> In general, the timestep depends on the acceleration field from the previous cycle, which is likely not what we want.

I'm not sure that there is an easy way to fix this without making a structural change to the `Cello` framework. My only thought is that we could hypothetically move the acceleration calculation into `EnzoMethodGravity::timestep`. However, this may be challenging because `EnzoMethodGravity::timestep` is labelled by `const` (this may not be an issue based on where counters for communication are stored). 

Take my response with a grain of salt (I don't have any experience with gravity methods so there might be other considerations too)

**Comment by stefanarridge** [comment]
Having thought about this a bit more, the use of the previous cycle's acceleration field is probably not that big an issue. However,it it is important to ensure that the accelerations are not zero for the first cycle. As far as I can tell, the best way around this is to compute the potential and acceleration fields for 'cycle 0'. This would have the advantage that these fields would be non-zero in the 'cycle 0 output', which would be useful for analysis purposes. I'm not sure how straightforward this would be to implement, however. 

I also still believe it would be beneficial to have a more physically motivated timestep function, which would relatively simple to implement, but may require some experimentation.
