### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by jwise77** [enzo-project/enzo-e#86]
On the front documentation page, some of the links (e.g. "Getting started", "Parameter file", "Parameter reference") within the text are broken.

**Comment by jobordner** [comment]
Thanks John.  I've updated all links on the live page (currently front page only, haven't checked other pages yet), though the updates still need to be propagated back to the master branch.

**Comment by mabruzzo** [comment]
I think that all of the links have been fixed (@jobordner pushed some relevant bugfixes at the end of April/start of May)
