### ISSUE TITLE
Possible issue with time integration of particles

### ISSUE THREAD

**Issue by stefanarridge** [enzo-project/enzo-e#95]
I have found some mismatches between what is written in the Enzo paper (https://arxiv.org/abs/1307.2265), and what is currently implemented in Enzo-E. 

Firstly, the paper describes the following procedure for depositing particles onto the grid:

" During the CIC interpolation, particle positions are (temporarily) advanced by 0.5vn∆t so that we generate an estimate of the time-centered density field.
"

However, lines 183-195 in src/Enzo/enzo_EnzoMethodPmDeposit.cpp are:

```

            double x = xa[ip*dp] + vxa[ip*dv]*dt;

            double tx = nx*(x - xm) / (xp - xm) - 0.5;

            int ix0 = gx + floor(tx);

            int ix1 = ix0 + 1;

            double x0 = 1.0 - (tx - floor(tx));
            double x1 = 1.0 - x0;

            de_p[ix0] += dens*x0;
            de_p[ix1] += dens*x1;
```

i.e. particles are drifted by the whole timestep before being deposited onto the grid.

EDIT:
It appears that dt is defined on Line 152 as follows:

```
const double dt = alpha_ * block->dt() / cosmo_a;
```
Where alpha_ is set to be 0.5 by default. So if the default value is used, there is agreement with the Enzo paper, but perhaps this should be hard-coded? Is there any reason why we would want to change it?

When it comes to updating the particles' positions and velocities, the paper describes a 'Drift-Kick-Drift' integration scheme (Equations 62). 
What is implemented in Enzo-E currently is a bit different. Firstly, the particles' accelerations are calculating by interpolating from the acceleration field to the particles' drifted positions, in lines 91-106 in src/Enzo/enzo_EnzoMethodPmUpdate.cpp:

```
 double dt_shift = 0.5*block->dt()/cosmo_a;
    //    double dt_shift = 0.0;
    if (rank >= 1) {
      EnzoComputeCicInterp interp_x ("acceleration_x", "dark", "ax", dt_shift);
      interp_x.compute(block);
    }

    if (rank >= 2) {
      EnzoComputeCicInterp interp_y ("acceleration_y", "dark", "ay", dt_shift);
      interp_y.compute(block);
    }

    if (rank >= 3) {
      EnzoComputeCicInterp interp_z ("acceleration_z", "dark", "az", dt_shift);
      interp_z.compute(block);
    }
```
EDIT: Also note that this is only done for "dark" particles at the moment. Extending this to other types of particles should be straightforward though.

Then, in lines 189-191 the particles' positions and velocities are updated with something that looks like a Kick-Drift-Kick integration scheme:

```
	  vx[ipdv] = cvv*vx[ipdv] + cva*ax[ipda];
	  x [ipdp] += cp*vx[ipdv];
	  vx[ipdv] = cvv*vx[ipdv] + cva*ax[ipda];

```

with cp, cvv and cva defined in lines 145-148:

```
    const double cp = dt/cosmo_a;
    const double coef = 0.25*cosmo_dadt/cosmo_a*dt;
    const double cvv = (1.0 - coef) / (1.0 + coef);
    const double cva = 0.5*dt / (1.0 + coef);
    
```

Even if we did decide to use Kick-Drift-Kick scheme, I'm not sure this is the right way to do it. The accelerations in the two kick steps should be different, and should be calculated using the particles' positions before/after the drift respectively.

Is this change from what's described in the Enzo paper intentional? I tried looking at the Enzo source code to figure out what is actually implemented in Enzo but I couldn't find the relevant lines of code.

**Comment by jobordner** [comment]
There was a discussion on the enzo-dev list in 2019 about ENZO using KDK instead of DKD; this is a known issue with the method paper.

**Comment by gregbryan** [comment]
Yes, I think James is correct here -- the current Enzo-E implementation does match the current Enzo code, but neither  matches the method paper. Apologies for the confusion. The Enzo-E method paper should correctly describe this (and the Enzo paper should be corrected...).
